module.exports = {
    SERVER_ERROR: 'SERVER_ERROR',
    NOT_FOUND: 'NOT_FOUND',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    INVALID_FIELDS: 'INVALID_FIELDS',
    INSERT_ELEMENT: 'INSERT_ELEMENT',
    JWT_EXPIRATION_INTERVAL: '30m'
};
